Document: carbon-c-relay
Title: Debian carbon-c-relay Manual
Author: <insert document author here>
Abstract: This manual describes what carbon-c-relay is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/carbon-c-relay/carbon-c-relay.sgml.gz

Format: postscript
Files: /usr/share/doc/carbon-c-relay/carbon-c-relay.ps.gz

Format: text
Files: /usr/share/doc/carbon-c-relay/carbon-c-relay.text.gz

Format: HTML
Index: /usr/share/doc/carbon-c-relay/html/index.html
Files: /usr/share/doc/carbon-c-relay/html/*.html
